// <auto-generated />
namespace ProductOdata.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addtale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtale));
        
        string IMigrationMetadata.Id
        {
            get { return "201501230826027_addtale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
