//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWeb.UploadFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://HsutonWong.com", ConfigurationName="UploadFileService.IUploadService")]
    public interface IUploadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HsutonWong.com/IUploadService/UploadPhotoInfo", ReplyAction="http://HsutonWong.com/IUploadService/UploadPhotoInfoResponse")]
        string UploadPhotoInfo(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HsutonWong.com/IUploadService/UploadPhotoInfo", ReplyAction="http://HsutonWong.com/IUploadService/UploadPhotoInfoResponse")]
        System.Threading.Tasks.Task<string> UploadPhotoInfoAsync(System.IO.Stream stream);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUploadServiceChannel : ClientWeb.UploadFileService.IUploadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadServiceClient : System.ServiceModel.ClientBase<ClientWeb.UploadFileService.IUploadService>, ClientWeb.UploadFileService.IUploadService {
        
        public UploadServiceClient() {
        }
        
        public UploadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UploadPhotoInfo(System.IO.Stream stream) {
            return base.Channel.UploadPhotoInfo(stream);
        }
        
        public System.Threading.Tasks.Task<string> UploadPhotoInfoAsync(System.IO.Stream stream) {
            return base.Channel.UploadPhotoInfoAsync(stream);
        }
    }
}
